# This file is for development work. Not suitable for production.
FROM php:8.1-apache

ARG USER_NAME=www-data
ARG USER_GROUP=www-data
ARG USER_ID=1000
ARG GROUP_ID=1000

# Use the default production configuration.
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

# Install gd extension.
RUN apt-get update && apt-get install --no-install-recommends -y  \
    libldap2-dev \
    libpng-dev \
    libfreetype6-dev \
    && rm -rf /var/lib/apt/lists/*
    
  
RUN docker-php-ext-configure gd --with-freetype \
 && docker-php-ext-install  \
    gd  \
    ldap \
    mysqli \
    && pecl install xdebug  \
    && docker-php-ext-enable xdebug

# Copy xdebug and php config.
COPY xdebug.ini /usr/local/etc/php/conf.d/

# Change www-data users uid and www-data groups gid
RUN usermod  --uid $USER_ID $USER_NAME && groupmod --gid $GROUP_ID $USER_GROUP

# set default user and working directory
USER www-data
WORKDIR /var/www/project