# This file is for development work. Not suitable for production.
FROM mariadb:latest

# Copy database creation script.
COPY mysql.sql /docker-entrypoint-initdb.d/

# Copy database population script, if available.
# TODO: design a better directory structure.
COPY populate.sql /docker-entrypoint-initdb.d/
